import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/app/_lib/utils";
import { Providers } from "./_components/providers";
import { Card, CardContent } from "./_components/ui/card";
const nunitoSans = Nunito_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        nunitoSans.variable,
      )}
    >
      <body className="min-h-full flex flex-col md:[&::-webkit-scrollbar]:hidden">
        <Providers>
          {children}
          {/* <footer>
            <Card>
              <CardContent>
                <p className=" text-gray-400">
                  © 2026 Copyright <strong>FSW Barber</strong>
                </p>
              </CardContent>
            </Card>
          </footer> */}
        </Providers>
      </body>
    </html>
  );
}
